bed_file: "regions.bed"

filter_thresholds:
  DP: 30
  GQ: 99

#######################
known_sites: "./Mills_and_1000G_gold_standard.indels.b37.vcf"
ref: "./GRCh37.p13.genome.fa"
docker_data: "./VEP_data"
bwa_index: "./GRCh37.p13.genome.fa"
